title: Channels
modelClass: NielsVanDenDries\Twitchembed\Models\Channel
list: $/nielsvandendries/twitchembed/models/channel/columns.yaml
recordUrl: 'nielsvandendries/twitchembed/channels/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
