title: Settings
modelClass: NielsVanDenDries\Twitchembed\Models\Settings
list: $/nielsvandendries/twitchembed/models/settings/columns.yaml
recordUrl: 'nielsvandendries/twitchembed/settings/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
